[package]
name = "command_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1.0", features = ["full", "extra-traits"] }
linkme = "0.3"
proc-macro2 = "1"
convert_case = "0.8.0"